### PR TITLE
Revert "Contributions"

### PR DESCRIPTION
**Pull request by mgold1234**
Reverts mgold1234/beyond-git-challange-mgold1234#1

### CODE REVIEW

**Comment by mgold1234** [comment]
please add 3 files of contributations again

**Comment by Yarboa** [comment]
> please add 3 files of contributations again

Cool did 
git fetch upstream refs/pull/2/head:contributions
Will propose a fix soon

**Comment by Yarboa** [comment]
Interesting i found this
https://tighten.co/blog/adding-commits-to-a-pull-request/
Will try it

**Comment by Yarboa** [comment]
> Interesting i found this
> https://tighten.co/blog/adding-commits-to-a-pull-request/
> Will try it

OK, so it is very good tutorial, but to push the following, is really pushing into the reverted branch,
Which i do not have permissions 
[yrachman@yrachman beyond-git-challange-mgold1234]$ git push mgold1234 revert-1-contributions
Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
ERROR: Permission to mgold1234/beyond-git-challange-mgold1234.git denied to Yarboa.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Which means, only solution for me is new PR, 
Please close this PR, we will continue here:

https://github.com/mgold1234/beyond-git-challange-mgold1234/pull/4

**Pull request closed without merging**
